[RTL]
itemTitle=Ride The Lightning
itemVersion=1.0
itemAuthor=NA
itemDescription=Rock Band Song
dataurl=https://rhythmverse.co/download_file/ghtorb3/516393c64c8c3/GHMFWTBT
path=Hdd1:\

#Hdd1:\Content\0000000000000000/45410914\00000001\
